services:
  # --- 1. CONFIGURATION SERVER (Infrastructure) ---
  config-server:
    build: ../Infrastructure/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/batteoui123/smart-delivery-config.git
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 30s

  # --- 2. DISCOVERY SERVICE (Eureka) ---
  discovery-service:
    build: ../Infrastructure/eureka-server
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      config-server:
        condition: service_healthy

  # --- 3. BASE DE DONNÉES (PostgreSQL) ---
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: smart_delivery_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  # --- 4. MESSAGE BROKER (Kafka + Zookeeper) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --- 5. API GATEWAY ---
  api-gateway:
    build: ../Infrastructure/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_started

  # --- 6. USER SERVICE (Métier) ---
  user-service:
    build: ../services/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user_db
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_started

  # --- 7. ORDER SERVICE (Métier) ---
  order-service:
    build: ../services/order-service
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka:
        condition: service_started

  # --- 8. DELIVERY SERVICE (Métier) ---
  delivery-service:
    build: ../services/delivery-service
    container_name: delivery-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/delivery_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka:
        condition: service_started
